### ISSUE TITLE
Clarify connect chat feature is deprecated

### ISSUE THREAD

**Issue by djuber** [forem/admin-docs#22]
### Explain the changes

The documentation at https://admin.forem.com/docs/advanced-customization/chat-channels describes the "connect" chat functionality. Since this is feature-flagged and deprecated, the page should clarify that this may not be available for all Forems (or removed entirely to avoid confusion?) The feature flag was intended to permit sites already using this to migrate to another solution (and is intended to be temporary). 
 
### Suggested changes

Either remove chat-channels.md or add clarifying language under the Overview heading that highlights this is a limited feature for some existing Forems, and likely not visible in most sites, or new Forems.  A link to Ben's [forem.dev](https://forem.dev/foremteam/deprecating-connect-chat-2kgi) post indicating the rationale might be useful.

**Comment by djuber** [comment]
Actually - when connect is disabled on Nov 17th, remove this page (I assume no need to add clarification in the meantime).

**Comment by michael-tharrington** [comment]
Done! Also removing Connect mentions from other parts of the docs
