### ISSUE TITLE
Update "Forem Setup Checklist" Documentation

### ISSUE THREAD

**Issue by juliannatetreault** [forem/admin-docs#26]
### Explain the changes
With the new-and-improved Creator Onboarding flow, the "Verify Setup" banner and "Getting Started" section are no longer as useful as they once were. This being said, we have removed the "Verify Setup" banner from the site and plan on removing the "Getting Started" section from the Config. In our Admin documentation, we have a [brief section](https://admin.forem.com/docs/getting-started/forem-setup-checklist#1-set-up-and-configure-your-forem) that explains both the "Verify Setup" banner and the "Getting Started" section in the Config. With the removal of both, we'll also want to remove the documentation for them.

### Suggested changes
The following changes will need to be made:
- We will need to remove the references to the "Verify Setup" banner and "Getting Started" section from the "Forem Setup Checklist" documentation, which can be found [here](https://admin.forem.com/docs/getting-started/forem-setup-checklist#1-set-up-and-configure-your-forem).

### Additional context
The [PR](https://github.com/forem/forem/pull/15969) for the removal of the "Verify Setup" banner has been merged, but the [PR](https://github.com/forem/forem/pull/16033) for the removal of the "Getting Started" section is in a draft mode and will remain in a draft mode until I speak with @Ridhwana further about how to best communicate this change. This being said, I will provide updates on when the work is actually merged so that we can coordinate the removal of the references to this section from the documentation (if that works for y'all!). 😊

**Comment by ellativity** [comment]
Thanks for this issue, @juliannatetreault 🙌

Since I don't run a local development instance of Forem, I can only take these screenshots when provisioning a new Forem. Is there any way you can make up-to-date duplicates of these images, please? Then I can modify the text and remove all visual references to the "Verify Setup" banner!

>Navigate to your Admin Portal by appending `/admin` to the homepage URL of your Forem (e.g. dev.to/admin) or selecting Admin from the dropdown menu under your profile image at the top-right of your screen:

![drop down menu screenshot](https://raw.githubusercontent.com/forem/admin-docs/main/static/img/firstDropdownAdmin.png)

And

>Navigate to `/admin/customization/config` using the Admin Navigation menu.

![admin/customization/config](https://raw.githubusercontent.com/forem/admin-docs/main/static/img/firstConfig.png)

Really appreciate your help here. I hope our next new Forem provisioning will coincide with the next PR, so we can create new screenshots of the process!

**Comment by juliannatetreault** [comment]
I can absolutely take screenshots for you, @ellativity!

>Really appreciate your help here.

Likewise! 😊

**Comment by juliannatetreault** [comment]
Here are the screenshots, @ellativity!

> Navigate to your Admin Portal by appending /admin to the homepage URL of your Forem (e.g. dev.to/admin) or selecting Admin from the dropdown menu under your profile image at the top-right of your screen:

<img width="1328" alt="Screen Shot 2022-01-20 at 9 51 17 AM" src="https://user-images.githubusercontent.com/32834804/150384553-37d4716c-1fcb-45b8-b522-c541028b7533.png">


> Navigate to /admin/customization/config using the Admin Navigation menu:

<img width="1478" alt="Screen Shot 2022-01-20 at 9 47 16 AM" src="https://user-images.githubusercontent.com/32834804/150383906-0456851a-29c7-4e16-b4d1-bcce9ba0d21d.png">


Feel free to update the documentation whenever, as the feature will be live on all Forems with the next deploy!

**Comment by ellativity** [comment]
Thanks @juliannatetreault

**Comment by juliannatetreault** [comment]
Thank YOU, @ellativity!!

**Comment by ellativity** [comment]
- Removed references to **Get Started** section and replaced relevant image (https://github.com/forem/forem/pull/16033)
- Removed references to "Verify Setup" banner and replaced relevant image (https://github.com/forem/forem/pull/15969)
- Updated reference to **Suggested Users** and **Suggested Tags** from **Get Started** to **Config > Onboarding** (https://github.com/forem/forem/pull/16228)
- Updated references to images ([as per this changelog](https://forem.dev/foremteam/changelog-new-creator-setup-process-and-image-improvements-4hc3))
