### ISSUE TITLE
Update Documentation Related to the Admin Member Detail View

### ISSUE THREAD

**Issue by juliannatetreault** [forem/admin-docs#28]
### Explain the changes
Once the updated Admin Member Detail View is live, any documentation referencing the Admin Member View, the ["User Roles" section screenshots](https://admin.forem.com/docs/forem-basics/user-roles), the ["Suspending Users" section](https://admin.forem.com/docs/managing-your-community/suspending-users), and the ["Removing Spam" section](https://admin.forem.com/docs/managing-your-community/removing-spam) to be precise, will need to be updated accordingly.

### Suggested changes
The following changes will need to be made:
- Updates to the documentation's copy, including references to links
- Updates to the documentation's pictures

### Additional context
The revamped Admin Member View will hopefully go live in the upcoming weeks, but the exact date is still TBD -- more updates to come! Additionally, I am more than happy to help where I can, so please let me know where and how I can be of assistance. 😊

**Comment by juliannatetreault** [comment]
Hey, @ellativity 👋  Pinging you here to see if you'd be open to coordinating on the Admin Member Detail View documentation in the near future! 😊

**Comment by ellativity** [comment]
I would love to coordinate with you @juliannatetreault! Thanks for asking!

**Comment by juliannatetreault** [comment]
> I would love to coordinate with you @juliannatetreault! Thanks for asking!

Yay! I look forward to it and will reach out on Slack as we get closer to the testing/launch date (but not _too_ close so that we have all the time we need). 😊

**Comment by Ridhwana** [comment]
Hey folks since this was implemented already, I hope you don't mind me closing this issue :)
