### ISSUE TITLE
Update `/advanced-customization/listings`

### ISSUE THREAD

**Issue by ellativity** [forem/admin-docs#31]
### Explain the changes

As @amywtlin describes [in this issue](https://github.com/forem/internalCommunity/issues/278), Listings are being placed behind a feature flag. We need to update the docs to reflect this change and instruct admins on how to enable Listings if they want to.

### Suggested changes

@jeremyf has written these instructions complete with screenshots: [How to enable the listing_feature](https://docs.google.com/document/d/1BvLKWymT0C_-r_x6ZMCVty9YuWq_yCxi36SLQZh_NSI/edit#)

### Additional context

This needs to happen by Friday 24 February 2022.

**Comment by amywtlin** [comment]
Based on the discussion [here](https://forem-team.slack.com/archives/CAA200SH5/p1645635120725449) we'll take a different route to bring a toggle for extensions like this, without having to update the doc. Hence closing it - thanks @ellativity
