### ISSUE TITLE
Make it clearer in "Editing a Tag" how to create and edit a template

### ISSUE THREAD

**Issue by abbyphoenix** [forem/admin-docs#33]
### Explain the changes

Update the [**Editing a Tag page**](https://admin.forem.com/docs/forem-basics/tags#editing-a-tag) to more clearly draw out that this is where you can find out how to create and edit a post template.

### Suggested changes

Update the first paragraph of the **Submission Template** section to read:

> **Submission Template**: This is where you create a post template! Place text here that will appear when you create any new posts under this tag. You can share these templates by directing people to /new/{tag_name}. This is especially useful when encouraging members to post about a topic in a structured format. This field takes markdown.

### Additional context

The reason I place that sentence right at the start is so that it shows up when you search the admin docs for "template" -- currently, it shows: "Submission Template: Placeholder text that appears when creating" -- which doesn't instantly clue in someone who's looking for information on creating templates that this is where to go. Assuming that the same general number of characters shows up in the search preview, it should now show: "Submission Template: This is where you create a post template!" -- which will be more eye-catching in the search preview.

**Comment by michael-tharrington** [comment]
Awesome thoughts! Done!
